countries = {
    "afghanistan": "Landlocked country at crossroads of Central and South Asia.",
    "albania": "Home to historic Berat and a Balkan coastline.",
    "algeria": "Africa’s largest country, mostly desert.",
    "andorra": "Tiny Pyrenean principality between France and Spain.",
    "angola": "Southern African nation rich in oil.",
    "antigua and barbuda": "Caribbean island nation known for beaches.",
    "argentina": "Famous for tango, gauchos, and Patagonia.",
    "armenia": "Landlocked Caucasus nation, oldest Christian state.",
    "australia": "Island continent known for kangaroos and reefs.",
    "austria": "Alpine country famed for classical music.",
    "azerbaijan": "Oil-rich Caspian nation with flame towers.",
    "bahamas": "Archipelago near Florida, known for clear waters.",
    "bahrain": "Gulf island kingdom with Formula 1 track.",
    "bangladesh": "Delta nation, home to the Sundarbans.",
    "barbados": "Cricket-loving Caribbean island.",
    "belarus": "Landlocked Eastern European nation, Minsk capital.",
    "belgium": "Home of waffles, chocolate and EU HQs.",
    "belize": "Central American Caribbean coast, jungle.",
    "benin": "Birthplace of voodoo religion in West Africa.",
    "bhutan": "Himalayan Buddhist kingdom emphasizing Gross Happiness.",
    "bolivia": "Landlocked with Salt Flats and Andes peaks.",
    "bosnia and herzegovina": "Balkan country with Sarajevo.",
    "botswana": "African safari destination with Okavango Delta.",
    "brazil": "Amazon rainforest giant and soccer powerhouse.",
    "brunei": "Wealthy tiny sultanate on Borneo.",
    "bulgaria": "Eastern European country on Black Sea.",
    "burkina faso": "Landlocked Western African nation.",
    "burundi": "Small, densely populated East African country.",
    "cambodia": "Home to Angkor Wat temple complex.",
    "cameroon": "Africa in miniature, variety of landscapes.",
    "canada": "Second-largest country, from Rockies to Arctic.",
    "cape verde": "Volcanic island nation off West Africa.",
    "central african republic": "Landlocked with rainforests.",
    "chad": "Landlocked in central Africa, huge lake.",
    "chile": "Long, narrow Pacific coast nation to Andes.",
    "china": "World’s most populous country.",
    "colombia": "Coffee-growing Andean and Caribbean nation.",
    "comoros": "Volcanic islands off East Africa.",
    "costa rica": "Biodiverse Central American eco-tourism hub.",
    "croatia": "Adriatic beaches and Dalmatian coast.",
    "cuba": "Caribbean island known for cigars and classic cars.",
    "cyprus": "Mediterranean island divided north and south.",
    "czechia": "Central European home to Prague’s castles.",
    "denmark": "Scandinavian kingdom of Vikings and hygge.",
    "djibouti": "Tiny Horn nation by Red Sea.",
    "dominica": "Caribbean “Nature Island” with rainforests.",
    "dominican republic": "Shared Hispaniola island with Haiti.",
    "ecuador": "Andean nation including Galápagos Islands.",
    "egypt": "Home of ancient pyramids and the Nile.",
    "el salvador": "Central America’s smallest country, volcanoes.",
    "equatorial guinea": "Central African oil-rich coastal nation.",
    "eritrea": "Horn of Africa nation with Red Sea coast.",
    "estonia": "Baltic digital-eager tech-forward country.",
    "eswatini": "Africa’s last absolute monarchy (formerly Swaziland).",
    "ethiopia": "Horn country, origin of coffee and ancient Axum.",
    "fiji": "South Pacific island paradise with coral reefs.",
    "finland": "Land of thousands of lakes and Saunas.",
    "france": "Tourist capital, Eiffel Tower and wine.",
    "gabon": "Equatorial forest nation in West-Central Africa.",
    "gambia": "Smallest African country, the Gambia River.",
    "georgia": "Caucasus nation, Tbilisi old town.",
    "germany": "European powerhouse of engineering and beer.",
    "ghana": "West African democracy with Cape Coast.",
    "greece": "Ancient ruins and Mediterranean islands.",
    "grenada": "Spice Isle in the Caribbean (nutmeg).",
    "guatemala": "Land of volcanoes and Mayan history.",
    "guinea": "West African nation with bauxite.",
    "guinea-bissau": "Archipelago and mainland in West Africa.",
    "guyana": "South American rainforest and waterfalls.",
    "haiti": "Caribbean nation sharing Hispaniola.",
    "honduras": "Central America with Mayan Copán ruins.",
    "hungary": "Home to Budapest’s thermal baths.",
    "iceland": "Volcanic, geysers, glaciers and Northern Lights.",
    "india": "Second most populous, Taj Mahal and Bollywood.",
    "indonesia": "Largest archipelago with temples and islands.",
    "iran": "Ancient Persia with ruins like Persepolis.",
    "iraq": "Mesopotamia cradle of civilization, Tigris·Euphrates.",
    "ireland": "Emerald Isle famed for green landscapes and pubs.",
    "israel": "Holy sites: Jerusalem, Dead Sea and Tel Aviv.",
    "italy": "Rome, pasta, Venice — eternal cultural heritage.",
    "jamaica": "Reggae birthplace and Blue Mountains coffee.",
    "japan": "Land of the rising sun, sushi and tech.",
    "jordan": "Wadi Rum and ancient Petra city.",
    "kazakhstan": "Largest landlocked country, Steppes and spaceport.",
    "kenya": "Wildlife safaris and Great Rift Valley.",
    "kiribati": "Pacific atoll nation at risk from sea levels.",
    "kosovo": "Youngest European de facto country.",
    "kuwait": "Rich oil emirate in the Arabian Gulf.",
    "kyrgyzstan": "Tian Shan mountains and nomadic culture.",
    "laos": "Landlocked Mekong River country.",
    "latvia": "Baltic nation with Riga Old Town.",
    "lebanon": "Mediterranean history and mountain cedar.",
    "lesotho": "High-altitude kingdom within South Africa.",
    "liberia": "Founded by freed American slaves.",
    "libya": "North African desert nation and oil fields.",
    "liechtenstein": "Tiny Alpine realm between Switzerland and Austria.",
    "lithuania": "Baltic country with medieval Vilnius.",
    "luxembourg": "Wealthy European microstate and Grand Duchy.",
    "madagascar": "Island off Africa, lemurs and rainforests.",
    "malawi": "Landlocked with Lake Malawi biodiversity.",
    "malaysia": "Twin skyscrapers and Borneo rainforest.",
    "maldives": "Indian Ocean atoll nation, honeymoon destination.",
    "mali": "Saharan desert and ancient Timbuktu.",
    "malta": "Mediterranean island with historic Valletta.",
    "marshall islands": "Pacific atolls with nuclear legacy.",
    "mauritania": "Sahara desert country in West Africa.",
    "mauritius": "Indian Ocean island paradise and dodo history.",
    "mexico": "Aztec ruins, beaches and spicy cuisine.",
    "micronesia": "Pacific federation of small island states.",
    "moldova": "Eastern European wine cellars.",
    "monaco": "Tiny Mediterranean principality, casinos and F1.",
    "mongolia": "Steppes, Genghis Khan and nomads.",
    "montenegro": "Adriatic coast, fjord-like bay of Kotor.",
    "morocco": "North Africa, souks and Atlas Mountains.",
    "mozambique": "Indian Ocean coast and marine life.",
    "myanmar": "Templed plains of Bagan in Southeast Asia.",
    "namibia": "Desert dunes and wildlife in Etosha.",
    "nauru": "World’s smallest island republic.",
    "nepal": "Home to Mount Everest and Himalayan trekking.",
    "netherlands": "Tulips, windmills and Amsterdam canals.",
    "new zealand": "Kiwi land of mountains and hobbits.",
    "nicaragua": "Lake Nicaragua and colonial Granada.",
    "niger": "Desert nation in West Africa.",
    "nigeria": "Africa’s most populous, Lagos megacity.",
    "north korea": "Hermit kingdom with strict regime.",
    "north macedonia": "Landlocked Balkan country, Skopje capital.",
    "norway": "Scandinavian fjords and midnight sun.",
    "oman": "Arabian Peninsula: deserts and frankincense.",
    "pakistan": "Indus Valley civilization and K2.",
    "palau": "Micronesian marine paradise, Rock Islands.",
    "panama": "Canal link between oceans.",
    "papua new guinea": "Island with diverse tribes and birds-of-paradise.",
    "paraguay": "Landlocked with large Indigenous Guarani population.",
    "peru": "Machu Picchu, Andes and Amazon basin.",
    "philippines": "7000+ tropical islands in Southeast Asia.",
    "poland": "Central Europe, medieval Kraków and WWII history.",
    "portugal": "Western Europe, azulejos and port wine city.",
    "qatar": "Tiny Gulf emirate, host of 2022 FIFA World Cup.",
    "romania": "Home to Transylvania and medieval castles.",
    "russia": "World’s largest country across Eurasia.",
    "rwanda": "Land of a thousand hills and mountain gorillas.",
    "saint kitts and nevis": "Twin volcanic Caribbean islands.",
    "saint lucia": "Pitons volcanic peaks in the Caribbean.",
    "saint vincent and the grenadines": "Archipelago sailing destination.",
    "samoa": "Polynesian island culture and rainforests.",
    "san marino": "One of the world’s oldest republics inside Italy.",
    "sao tome and principe": "Equatorial Atlantic islands rich in forests.",
    "saudi arabia": "Birthplace of Islam, Mecca and desert.",
    "senegal": "West African music and Goree Island.",
    "serbia": "Balkan nation with Belgrade nightlife.",
    "seychelles": "Beautiful Indian Ocean granite islands.",
    "sierra leone": "West African nation with beaches and history.",
    "singapore": "City-state of skyscrapers and hawker food.",
    "slovakia": "Carpathian Mountains, Bratislava Old Town.",
    "slovenia": "Lake Bled Alpine scenescape.",
    "solomon islands": "WWII Pacific island chain.",
    "somalia": "Horn of Africa nation on Indian Ocean.",
    "south africa": "Rainbow Nation, Cape Town and safaris.",
    "south korea": "Tech powerhouse, K‑pop, Seoul.",
    "south sudan": "World’s youngest country in Africa.",
    "spain": "Flamenco, tapas and Mediterranean coast.",
    "sri lanka": "Tropical island with tea plantations.",
    "sudan": "Nile and ancient Nubian pyramids.",
    "suriname": "Smallest country in South America.",
    "sweden": "Scandinavian monarchy, Stockholm’s archipelago.",
    "switzerland": "Alpine chocolates, watches, neutrality.",
    "syria": "Ancient ruins like Palmyra in the Levant.",
    "taiwan": "Tech hub and night-market culture.",
    "tajikistan": "High mountains in Central Asia.",
    "tanzania": "Mount Kilimanjaro and Serengeti safaris.",
    "thailand": "Tropical beaches, temples and street food.",
    "togo": "Small strip of land in West Africa.",
    "tonga": "Polynesian kingdom with friendly culture.",
    "trinidad and tobago": "Carnival island of steel drums.",
    "tunisia": "Mediterranean and Sahara heritage sites.",
    "turkey": "Crossroads of Europe and Asia, Istanbul.",
    "turkmenistan": "Desert nation with door to Hell crater.",
    "tuvalu": "Tiny Pacific islands threatened by sea rise.",
    "uganda": "Source of the Nile and mountain gorillas.",
    "ukraine": "Europe’s breadbasket and rich history.",
    "united arab emirates": "Gulf skyscrapers, Dubai and Abu Dhabi.",
    "united kingdom": "England, Scotland, Wales, Northern Ireland.",
    "united states": "North American superpower with states.",
    "uruguay": "South American beach and tango nation.",
    "uzbekistan": "Silk Road cities Samarkand & Bukhara.",
    "vanuatu": "Volcanic South Pacific archipelago.",
    "venezuela": "Angel Falls and oil-rich Caribbean coast.",
    "vietnam": "Rice paddies, Halong Bay and pho.",
    "yemen": "Historic Arabian peninsula port of Aden.",
    "zambia": "Victoria Falls and Zambezi River.",
    "zimbabwe": "Great Zimbabwe ruins and Victoria Falls."
}

